# Puerto del servidor
server.port=8080

# Conexión a MySQL (¡Asegúrate del puerto: 3306 o 3307!)
spring.datasource.url=jdbc:mysql://localhost:3306/netbook_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Nota: La línea del dialecto ya no es estrictamente necesaria en versiones modernas, 
# pero si quieres dejarla, está bien.